// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {command} from '../models';
import {app} from '../models';

export function GetKubectlInfo():Promise<command.CommandInfo>;

export function ListContainers(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function ListContexts():Promise<Array<string>>;

export function ListNamespaces(arg1:string):Promise<Array<string>>;

export function ListPods(arg1:string,arg2:string):Promise<Array<string>>;

export function OpenExec(arg1:app.ExecRequest):Promise<void>;

export function OpenPortForward(arg1:app.PortForwardRequest):Promise<void>;
