// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {command} from '../models';

export function GetKubectlInfo():Promise<command.CommandInfo>;
